name: heatchmap
dependencies:
  - pip
  - python=3.10
  - pip:
    - affine==2.4.0
    - asttokens==2.4.0
    - attrs==23.1.0
    - backcall==0.2.0
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.7
    - click-plugins==1.1.1
    - cligj==0.7.2
    - comm==0.1.4
    - contourpy==1.1.1
    - cycler==0.12.0
    - debugpy==1.8.0
    - decorator==5.1.1
    - exceptiongroup==1.1.3
    - executing==1.2.0
    - fastjsonschema==2.18.0
    - Fiona==1.9.4.post1
    - fonttools==4.43.0
    - geodatasets==2023.3.0
    - geopandas==0.14.0
    - idna==3.4
    - ipykernel==6.25.2
    - ipython==8.16.0
    - ipywidgets
    - jedi==0.19.0
    - jsonschema==4.19.1
    - jsonschema-specifications==2023.7.1
    - jupyter_client==8.3.1
    - jupyter_core==5.3.2
    - kiwisolver==1.4.5
    - matplotlib==3.8.0
    - matplotlib-inline==0.1.6
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - networkx==3.1
    - numpy==1.26.0
    - osmnx==1.7.0
    - packaging==23.1
    - pandas==2.1.1
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - Pillow==10.0.1
    - platformdirs==3.10.0
    - plotly==5.17.0
    - pooch==1.7.0
    - prompt-toolkit==3.0.39
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - Pygments==2.16.1
    - pyparsing==3.1.1
    - pyproj==3.6.1
    - pyshp==2.3.1
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - PyYAML==6.0
    - pyzmq==25.1.1
    - rasterio==1.3.8.post2
    - referencing==0.30.2
    - requests==2.31.0
    - rpds-py==0.10.3
    - Rtree==1.0.1
    - seaborn==0.13.0
    - shapely==2.0.2
    - six==1.16.0
    - scikit-learn
    - snuggs==1.4.7
    - stack-data==0.6.2
    - tenacity==8.2.3
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.10.1
    - tzdata==2023.3
    - urllib3==2.0.5
    - wcwidth==0.2.8